### ISSUE TITLE
Na versão 4.0.3 do Tema porto não está funcionando

### ISSUE THREAD

**Issue by EduuhAlvs** [luizbills/wc-better-shipping-calculator-for-brazil#2]
Tô usando porto 4.0.3
Woocommerce 3.2.4
Wordpress 4.9 
Não funcionou no tema.

**Comment by luizbills** [comment]
Testei aqui e ainda continua funcionando perfeitamente com o Porto. Tente limpar seu cache.

**Comment by EduuhAlvs** [comment]
Acho estranho, pois ja limpei cache e testei de várias formas e sem sucesso
até o momento.

2017-11-21 10:34 GMT-03:00 luizbills <notifications@github.com>:

**Comment by luizbills** [comment]
Uma pena. Deve ser algum plugin que vc tem instalado.
Mas o que acontece? Os campos não somem ou o CEP não é calculado?

**Comment by EduuhAlvs** [comment]
apenas os campos não somem de forma alguma, ja realizei teste desativando
os plugins


2017-11-22 12:42 GMT-03:00 luizbills <notifications@github.com>:

**Comment by luizbills** [comment]
Abra o *console* do seu navegador (F12) e veja se está tendo erros de javascript (algum outro plugin está causando erros). Se houver erros, desative todos os plugins exceto o WooCommerce e o **meu plugin**. Vá ativando outros plugin UM POR UM, para descobrir qual está causando o erro.
