### ISSUE TITLE
Não funcionou no meu tema (Route)

### ISSUE THREAD

**Issue by woozdigital** [luizbills/wc-better-shipping-calculator-for-brazil#3]
Meu tema é o Route:
https://themeforest.net/item/route-responsive-multipurpose-wordpress-theme/8815770

Eu uso teu plugin no The7 e ele funciona com soberania.

Mas neste tema não funcionou... 

Será que a gente consegue resolver isto?

Abraços!

**Comment by luizbills** [comment]
Aparece alguma mensagem de erro?

**Comment by woozdigital** [comment]
Não, simplesmente não remove os campos estado e país. É como se o teu plugin nem existisse

**Comment by luizbills** [comment]
Já testou com todos os plugins desativados (exceto o woocommerce e o meu)?

**Comment by woozdigital** [comment]
![captura de tela 2018-03-01 as 17 17 00](https://user-images.githubusercontent.com/36968845/36867681-9948f8a4-1d74-11e8-9724-0fe9b78de018.png)
Acabei de testar, mas não adiantou...

**Comment by woozdigital** [comment]
https://deleonstore.com.br

**Comment by luizbills** [comment]
Me envia uma cópia do tema para o meu e-mail luizpbills@gmail.com então, que assim que eu puder eu vou dar uma olhada.

**Comment by woozdigital** [comment]
Só baixar aqui: 
deleonstore.com.br/route.zip

**Comment by woozdigital** [comment]
Eu não me orgulho disso, mas por enquanto vou usar esse CSS:

#calc_shipping_country, #calc_shipping_state {
    display: none;
}

Só pra você saber, aí é só remover no Inspecionar Elemento. ;)
