### ISSUE TITLE
Ajuda - omitir o nome do estado e aparecer o nome da área cadastrada

### ISSUE THREAD

**Issue by pedrosan84** [luizbills/wc-better-shipping-calculator-for-brazil#9]
Oi, tudo bom? Meu nome é Pedro e queria a sua ajuda. Estou finalizando um e-commerce simples, para entrega de produtos apenas na cidade. Todos os ceps cadastrados são apenas de Nova Friburgo. Porém quando insiro o CEP na calculadora, aparece RIO DE JANEIRO (o estado), como posso fazer para aparecer o nome do bairro (no caso é o nome da área cadastrada). Você consegue me ajudar por favor?

![image](https://user-images.githubusercontent.com/34515281/83812974-da87f280-a692-11ea-8bb4-7a100f39de22.png)

**Comment by luizbills** [comment]
Me envia um e-mail em luizpbills@gmail.com com essas informações que irei fazer um orçamento para você ainda essa semana.
